name: CI
on:
- push
- pull_request
env:
  EXPORT_DIR: exported-artifacts
jobs:
  lint:
    runs-on: ubuntu-latest
    container: quay.io/alesgar/userstorage-test-centos-8
    steps:
    - uses: actions/checkout@v3
    - name: Run linters
      run: tox -e flake8,pylint
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: quay.io/alesgar/userstorage-test-centos-8
      # Required to create loop devices.
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: ci/test.sh
